pipeline {

    agent any
    stages {
        stage('Maven install') {
        steps {
          withMaven(globalMavenSettingsConfig: '--- Use system default settings or file path ---', jdk: 'JDK installtion', maven: 'Maven', mavenSettingsConfig: '--- Use system default settings or file path ---') {
            sh 'mvn clean install'
          }
        }
      }
    }


}
